name       : ebook-tools
version    : 0.2.2
release    : 3
source     :
    - https://nchc.dl.sourceforge.net/project/ebook-tools/ebook-tools/0.2.2/ebook-tools-0.2.2.tar.gz : cbc35996e911144fa62925366ad6a6212d6af2588f1e39075954973bbee627ae
license    : MIT
component  : programming
summary    : Tools for accessing various ebook file formats
description: |
    Tools for accessing various ebook file formats
builddeps  :
    - pkgconfig(libzip)
    - doxygen
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    # Requires convertlit, but not currently needed
    rm $installdir/usr/bin/lit2epub
